export interface Country {
  name: string;
  emoji: string;
  code: string;
}

export const countries: Country[] = [
  { name: "Afghanistan", emoji: "🇦🇫", code: "AF" },
  { name: "Albania", emoji: "🇦🇱", code: "AL" },
  { name: "Algeria", emoji: "🇩🇿", code: "DZ" },
  { name: "Andorra", emoji: "🇦🇩", code: "AD" },
  { name: "Angola", emoji: "🇦🇴", code: "AO" },
  { name: "Argentina", emoji: "🇦🇷", code: "AR" },
  { name: "Armenia", emoji: "🇦🇲", code: "AM" },
  { name: "Australia", emoji: "🇦🇺", code: "AU" },
  { name: "Austria", emoji: "🇦🇹", code: "AT" },
  { name: "Azerbaijan", emoji: "🇦🇿", code: "AZ" },
  { name: "Bahrain", emoji: "🇧🇭", code: "BH" },
  { name: "Bangladesh", emoji: "🇧🇩", code: "BD" },
  { name: "Belarus", emoji: "🇧🇾", code: "BY" },
  { name: "Belgium", emoji: "🇧🇪", code: "BE" },
  { name: "Benin", emoji: "🇧🇯", code: "BJ" },
  { name: "Bolivia", emoji: "🇧🇴", code: "BO" },
  { name: "Bosnia and Herzegovina", emoji: "🇧🇦", code: "BA" },
  { name: "Brazil", emoji: "🇧🇷", code: "BR" },
  { name: "Bulgaria", emoji: "🇧🇬", code: "BG" },
  { name: "Burkina Faso", emoji: "🇧🇫", code: "BF" },
  { name: "Burundi", emoji: "🇧🇮", code: "BI" },
  { name: "Cambodia", emoji: "🇰🇭", code: "KH" },
  { name: "Cameroon", emoji: "🇨🇲", code: "CM" },
  { name: "Canada", emoji: "🇨🇦", code: "CA" },
  { name: "Cape Verde", emoji: "🇨🇻", code: "CV" },
  { name: "Central African Republic", emoji: "🇨🇫", code: "CF" },
  { name: "Chad", emoji: "🇹🇩", code: "TD" },
  { name: "Chile", emoji: "🇨🇱", code: "CL" },
  { name: "China", emoji: "🇨🇳", code: "CN" },
  { name: "Colombia", emoji: "🇨🇴", code: "CO" },
  { name: "Comoros", emoji: "🇰🇲", code: "KM" },
  { name: "Congo", emoji: "🇨🇬", code: "CG" },
  { name: "Costa Rica", emoji: "🇨🇷", code: "CR" },
  { name: "Croatia", emoji: "🇭🇷", code: "HR" },
  { name: "Cuba", emoji: "🇨🇺", code: "CU" },
  { name: "Cyprus", emoji: "🇨🇾", code: "CY" },
  { name: "Czech Republic", emoji: "🇨🇿", code: "CZ" },
  { name: "DR Congo", emoji: "🇨🇩", code: "CD" },
  { name: "Denmark", emoji: "🇩🇰", code: "DK" },
  { name: "Ecuador", emoji: "🇪🇨", code: "EC" },
  { name: "Egypt", emoji: "🇪🇬", code: "EG" },
  { name: "El Salvador", emoji: "🇸🇻", code: "SV" },
  { name: "England", emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", code: "GB-ENG" },
  { name: "Equatorial Guinea", emoji: "🇬🇶", code: "GQ" },
  { name: "Eritrea", emoji: "🇪🇷", code: "ER" },
  { name: "Estonia", emoji: "🇪🇪", code: "EE" },
  { name: "Ethiopia", emoji: "🇪🇹", code: "ET" },
  { name: "Finland", emoji: "🇫🇮", code: "FI" },
  { name: "France", emoji: "🇫🇷", code: "FR" },
  { name: "Gabon", emoji: "🇬🇦", code: "GA" },
  { name: "Gambia", emoji: "🇬🇲", code: "GM" },
  { name: "Georgia", emoji: "🇬🇪", code: "GE" },
  { name: "Germany", emoji: "🇩🇪", code: "DE" },
  { name: "Ghana", emoji: "🇬🇭", code: "GH" },
  { name: "Greece", emoji: "🇬🇷", code: "GR" },
  { name: "Guatemala", emoji: "🇬🇹", code: "GT" },
  { name: "Guinea", emoji: "🇬🇳", code: "GN" },
  { name: "Guinea-Bissau", emoji: "🇬🇼", code: "GW" },
  { name: "Haiti", emoji: "🇭🇹", code: "HT" },
  { name: "Honduras", emoji: "🇭🇳", code: "HN" },
  { name: "Hungary", emoji: "🇭🇺", code: "HU" },
  { name: "Iceland", emoji: "🇮🇸", code: "IS" },
  { name: "India", emoji: "🇮🇳", code: "IN" },
  { name: "Indonesia", emoji: "🇮🇩", code: "ID" },
  { name: "Iran", emoji: "🇮🇷", code: "IR" },
  { name: "Iraq", emoji: "🇮🇶", code: "IQ" },
  { name: "Ireland", emoji: "🇮🇪", code: "IE" },
  { name: "Israel", emoji: "🇮🇱", code: "IL" },
  { name: "Italy", emoji: "🇮🇹", code: "IT" },
  { name: "Ivory Coast", emoji: "🇨🇮", code: "CI" },
  { name: "Jamaica", emoji: "🇯🇲", code: "JM" },
  { name: "Japan", emoji: "🇯🇵", code: "JP" },
  { name: "Jordan", emoji: "🇯🇴", code: "JO" },
  { name: "Kazakhstan", emoji: "🇰🇿", code: "KZ" },
  { name: "Kenya", emoji: "🇰🇪", code: "KE" },
  { name: "Kosovo", emoji: "🇽🇰", code: "XK" },
  { name: "Kuwait", emoji: "🇰🇼", code: "KW" },
  { name: "Latvia", emoji: "🇱🇻", code: "LV" },
  { name: "Lebanon", emoji: "🇱🇧", code: "LB" },
  { name: "Liberia", emoji: "🇱🇷", code: "LR" },
  { name: "Libya", emoji: "🇱🇾", code: "LY" },
  { name: "Lithuania", emoji: "🇱🇹", code: "LT" },
  { name: "Luxembourg", emoji: "🇱🇺", code: "LU" },
  { name: "Madagascar", emoji: "🇲🇬", code: "MG" },
  { name: "Malawi", emoji: "🇲🇼", code: "MW" },
  { name: "Malaysia", emoji: "🇲🇾", code: "MY" },
  { name: "Mali", emoji: "🇲🇱", code: "ML" },
  { name: "Malta", emoji: "🇲🇹", code: "MT" },
  { name: "Mauritania", emoji: "🇲🇷", code: "MR" },
  { name: "Mexico", emoji: "🇲🇽", code: "MX" },
  { name: "Moldova", emoji: "🇲🇩", code: "MD" },
  { name: "Montenegro", emoji: "🇲🇪", code: "ME" },
  { name: "Morocco", emoji: "🇲🇦", code: "MA" },
  { name: "Mozambique", emoji: "🇲🇿", code: "MZ" },
  { name: "Namibia", emoji: "🇳🇦", code: "NA" },
  { name: "Netherlands", emoji: "🇳🇱", code: "NL" },
  { name: "New Zealand", emoji: "🇳🇿", code: "NZ" },
  { name: "Nicaragua", emoji: "🇳🇮", code: "NI" },
  { name: "Niger", emoji: "🇳🇪", code: "NE" },
  { name: "Nigeria", emoji: "🇳🇬", code: "NG" },
  { name: "North Korea", emoji: "🇰🇵", code: "KP" },
  { name: "North Macedonia", emoji: "🇲🇰", code: "MK" },
  { name: "Northern Ireland", emoji: "🇬🇧", code: "GB-NIR" },
  { name: "Norway", emoji: "🇳🇴", code: "NO" },
  { name: "Oman", emoji: "🇴🇲", code: "OM" },
  { name: "Pakistan", emoji: "🇵🇰", code: "PK" },
  { name: "Palestine", emoji: "🇵🇸", code: "PS" },
  { name: "Panama", emoji: "🇵🇦", code: "PA" },
  { name: "Paraguay", emoji: "🇵🇾", code: "PY" },
  { name: "Peru", emoji: "🇵🇪", code: "PE" },
  { name: "Philippines", emoji: "🇵🇭", code: "PH" },
  { name: "Poland", emoji: "🇵🇱", code: "PL" },
  { name: "Portugal", emoji: "🇵🇹", code: "PT" },
  { name: "Qatar", emoji: "🇶🇦", code: "QA" },
  { name: "Romania", emoji: "🇷🇴", code: "RO" },
  { name: "Russia", emoji: "🇷🇺", code: "RU" },
  { name: "Rwanda", emoji: "🇷🇼", code: "RW" },
  { name: "Saudi Arabia", emoji: "🇸🇦", code: "SA" },
  { name: "Scotland", emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", code: "GB-SCT" },
  { name: "Senegal", emoji: "🇸🇳", code: "SN" },
  { name: "Serbia", emoji: "🇷🇸", code: "RS" },
  { name: "Sierra Leone", emoji: "🇸🇱", code: "SL" },
  { name: "Singapore", emoji: "🇸🇬", code: "SG" },
  { name: "Slovakia", emoji: "🇸🇰", code: "SK" },
  { name: "Slovenia", emoji: "🇸🇮", code: "SI" },
  { name: "Somalia", emoji: "🇸🇴", code: "SO" },
  { name: "South Africa", emoji: "🇿🇦", code: "ZA" },
  { name: "South Korea", emoji: "🇰🇷", code: "KR" },
  { name: "South Sudan", emoji: "🇸🇸", code: "SS" },
  { name: "Spain", emoji: "🇪🇸", code: "ES" },
  { name: "Sudan", emoji: "🇸🇩", code: "SD" },
  { name: "Sweden", emoji: "🇸🇪", code: "SE" },
  { name: "Switzerland", emoji: "🇨🇭", code: "CH" },
  { name: "Syria", emoji: "🇸🇾", code: "SY" },
  { name: "Tanzania", emoji: "🇹🇿", code: "TZ" },
  { name: "Thailand", emoji: "🇹🇭", code: "TH" },
  { name: "Togo", emoji: "🇹🇬", code: "TG" },
  { name: "Trinidad and Tobago", emoji: "🇹🇹", code: "TT" },
  { name: "Tunisia", emoji: "🇹🇳", code: "TN" },
  { name: "Turkey", emoji: "🇹🇷", code: "TR" },
  { name: "Uganda", emoji: "🇺🇬", code: "UG" },
  { name: "Ukraine", emoji: "🇺🇦", code: "UA" },
  { name: "United Arab Emirates", emoji: "🇦🇪", code: "AE" },
  { name: "United States", emoji: "🇺🇸", code: "US" },
  { name: "Uruguay", emoji: "🇺🇾", code: "UY" },
  { name: "Uzbekistan", emoji: "🇺🇿", code: "UZ" },
  { name: "Venezuela", emoji: "🇻🇪", code: "VE" },
  { name: "Vietnam", emoji: "🇻🇳", code: "VN" },
  { name: "Wales", emoji: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", code: "GB-WLS" },
  { name: "Yemen", emoji: "🇾🇪", code: "YE" },
  { name: "Zambia", emoji: "🇿🇲", code: "ZM" },
  { name: "Zimbabwe", emoji: "🇿🇼", code: "ZW" },
];

export function searchCountries(query: string): Country[] {
  if (!query) return countries.slice(0, 10);
  // Strip any leading emoji/flag characters for search (including regional indicators and tag sequences)
  const cleanQuery = query
    .replace(/^[\u{1F1E0}-\u{1F1FF}\u{1F3F4}\u{E0061}-\u{E007F}]+/u, "") // Regional indicators and tag sequences
    .replace(/^[\p{Emoji}\p{Emoji_Modifier}\p{Emoji_Component}\p{Emoji_Modifier_Base}\p{Emoji_Presentation}]+/u, "") // Other emojis
    .trim();
  if (!cleanQuery) return countries.slice(0, 10);
  const lowerQuery = cleanQuery.toLowerCase();
  return countries.filter((c) => c.name.toLowerCase().includes(lowerQuery));
}

export function getCountryByCode(code: string): Country | undefined {
  return countries.find((c) => c.code === code);
}

export function getCountryByEmoji(emoji: string): Country | undefined {
  return countries.find((c) => c.emoji === emoji);
}

export function getEmojiForCode(code: string): string | null {
  const country = getCountryByCode(code);
  return country ? country.emoji : null;
}
