export interface Country {
  name: string;
  emoji: string;
}

export const countries: Country[] = [
  { name: "Afghanistan", emoji: "🇦🇫" },
  { name: "Albania", emoji: "🇦🇱" },
  { name: "Algeria", emoji: "🇩🇿" },
  { name: "Andorra", emoji: "🇦🇩" },
  { name: "Angola", emoji: "🇦🇴" },
  { name: "Argentina", emoji: "🇦🇷" },
  { name: "Armenia", emoji: "🇦🇲" },
  { name: "Australia", emoji: "🇦🇺" },
  { name: "Austria", emoji: "🇦🇹" },
  { name: "Azerbaijan", emoji: "🇦🇿" },
  { name: "Bahrain", emoji: "🇧🇭" },
  { name: "Bangladesh", emoji: "🇧🇩" },
  { name: "Belarus", emoji: "🇧🇾" },
  { name: "Belgium", emoji: "🇧🇪" },
  { name: "Benin", emoji: "🇧🇯" },
  { name: "Bolivia", emoji: "🇧🇴" },
  { name: "Bosnia and Herzegovina", emoji: "🇧🇦" },
  { name: "Brazil", emoji: "🇧🇷" },
  { name: "Bulgaria", emoji: "🇧🇬" },
  { name: "Burkina Faso", emoji: "🇧🇫" },
  { name: "Burundi", emoji: "🇧🇮" },
  { name: "Cambodia", emoji: "🇰🇭" },
  { name: "Cameroon", emoji: "🇨🇲" },
  { name: "Canada", emoji: "🇨🇦" },
  { name: "Cape Verde", emoji: "🇨🇻" },
  { name: "Central African Republic", emoji: "🇨🇫" },
  { name: "Chad", emoji: "🇹🇩" },
  { name: "Chile", emoji: "🇨🇱" },
  { name: "China", emoji: "🇨🇳" },
  { name: "Colombia", emoji: "🇨🇴" },
  { name: "Comoros", emoji: "🇰🇲" },
  { name: "Congo", emoji: "🇨🇬" },
  { name: "Costa Rica", emoji: "🇨🇷" },
  { name: "Croatia", emoji: "🇭🇷" },
  { name: "Cuba", emoji: "🇨🇺" },
  { name: "Cyprus", emoji: "🇨🇾" },
  { name: "Czech Republic", emoji: "🇨🇿" },
  { name: "DR Congo", emoji: "🇨🇩" },
  { name: "Denmark", emoji: "🇩🇰" },
  { name: "Ecuador", emoji: "🇪🇨" },
  { name: "Egypt", emoji: "🇪🇬" },
  { name: "El Salvador", emoji: "🇸🇻" },
  { name: "England", emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { name: "Equatorial Guinea", emoji: "🇬🇶" },
  { name: "Eritrea", emoji: "🇪🇷" },
  { name: "Estonia", emoji: "🇪🇪" },
  { name: "Ethiopia", emoji: "🇪🇹" },
  { name: "Finland", emoji: "🇫🇮" },
  { name: "France", emoji: "🇫🇷" },
  { name: "Gabon", emoji: "🇬🇦" },
  { name: "Gambia", emoji: "🇬🇲" },
  { name: "Georgia", emoji: "🇬🇪" },
  { name: "Germany", emoji: "🇩🇪" },
  { name: "Ghana", emoji: "🇬🇭" },
  { name: "Greece", emoji: "🇬🇷" },
  { name: "Guatemala", emoji: "🇬🇹" },
  { name: "Guinea", emoji: "🇬🇳" },
  { name: "Guinea-Bissau", emoji: "🇬🇼" },
  { name: "Haiti", emoji: "🇭🇹" },
  { name: "Honduras", emoji: "🇭🇳" },
  { name: "Hungary", emoji: "🇭🇺" },
  { name: "Iceland", emoji: "🇮🇸" },
  { name: "India", emoji: "🇮🇳" },
  { name: "Indonesia", emoji: "🇮🇩" },
  { name: "Iran", emoji: "🇮🇷" },
  { name: "Iraq", emoji: "🇮🇶" },
  { name: "Ireland", emoji: "🇮🇪" },
  { name: "Israel", emoji: "🇮🇱" },
  { name: "Italy", emoji: "🇮🇹" },
  { name: "Ivory Coast", emoji: "🇨🇮" },
  { name: "Jamaica", emoji: "🇯🇲" },
  { name: "Japan", emoji: "🇯🇵" },
  { name: "Jordan", emoji: "🇯🇴" },
  { name: "Kazakhstan", emoji: "🇰🇿" },
  { name: "Kenya", emoji: "🇰🇪" },
  { name: "Kosovo", emoji: "🇽🇰" },
  { name: "Kuwait", emoji: "🇰🇼" },
  { name: "Latvia", emoji: "🇱🇻" },
  { name: "Lebanon", emoji: "🇱🇧" },
  { name: "Liberia", emoji: "🇱🇷" },
  { name: "Libya", emoji: "🇱🇾" },
  { name: "Lithuania", emoji: "🇱🇹" },
  { name: "Luxembourg", emoji: "🇱🇺" },
  { name: "Madagascar", emoji: "🇲🇬" },
  { name: "Malawi", emoji: "🇲🇼" },
  { name: "Malaysia", emoji: "🇲🇾" },
  { name: "Mali", emoji: "🇲🇱" },
  { name: "Malta", emoji: "🇲🇹" },
  { name: "Mauritania", emoji: "🇲🇷" },
  { name: "Mexico", emoji: "🇲🇽" },
  { name: "Moldova", emoji: "🇲🇩" },
  { name: "Montenegro", emoji: "🇲🇪" },
  { name: "Morocco", emoji: "🇲🇦" },
  { name: "Mozambique", emoji: "🇲🇿" },
  { name: "Namibia", emoji: "🇳🇦" },
  { name: "Netherlands", emoji: "🇳🇱" },
  { name: "New Zealand", emoji: "🇳🇿" },
  { name: "Nicaragua", emoji: "🇳🇮" },
  { name: "Niger", emoji: "🇳🇪" },
  { name: "Nigeria", emoji: "🇳🇬" },
  { name: "North Korea", emoji: "🇰🇵" },
  { name: "North Macedonia", emoji: "🇲🇰" },
  { name: "Northern Ireland", emoji: "🇬🇧" },
  { name: "Norway", emoji: "🇳🇴" },
  { name: "Oman", emoji: "🇴🇲" },
  { name: "Pakistan", emoji: "🇵🇰" },
  { name: "Palestine", emoji: "🇵🇸" },
  { name: "Panama", emoji: "🇵🇦" },
  { name: "Paraguay", emoji: "🇵🇾" },
  { name: "Peru", emoji: "🇵🇪" },
  { name: "Philippines", emoji: "🇵🇭" },
  { name: "Poland", emoji: "🇵🇱" },
  { name: "Portugal", emoji: "🇵🇹" },
  { name: "Qatar", emoji: "🇶🇦" },
  { name: "Romania", emoji: "🇷🇴" },
  { name: "Russia", emoji: "🇷🇺" },
  { name: "Rwanda", emoji: "🇷🇼" },
  { name: "Saudi Arabia", emoji: "🇸🇦" },
  { name: "Scotland", emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { name: "Senegal", emoji: "🇸🇳" },
  { name: "Serbia", emoji: "🇷🇸" },
  { name: "Sierra Leone", emoji: "🇸🇱" },
  { name: "Singapore", emoji: "🇸🇬" },
  { name: "Slovakia", emoji: "🇸🇰" },
  { name: "Slovenia", emoji: "🇸🇮" },
  { name: "Somalia", emoji: "🇸🇴" },
  { name: "South Africa", emoji: "🇿🇦" },
  { name: "South Korea", emoji: "🇰🇷" },
  { name: "South Sudan", emoji: "🇸🇸" },
  { name: "Spain", emoji: "🇪🇸" },
  { name: "Sudan", emoji: "🇸🇩" },
  { name: "Sweden", emoji: "🇸🇪" },
  { name: "Switzerland", emoji: "🇨🇭" },
  { name: "Syria", emoji: "🇸🇾" },
  { name: "Tanzania", emoji: "🇹🇿" },
  { name: "Thailand", emoji: "🇹🇭" },
  { name: "Togo", emoji: "🇹🇬" },
  { name: "Trinidad and Tobago", emoji: "🇹🇹" },
  { name: "Tunisia", emoji: "🇹🇳" },
  { name: "Turkey", emoji: "🇹🇷" },
  { name: "Uganda", emoji: "🇺🇬" },
  { name: "Ukraine", emoji: "🇺🇦" },
  { name: "United Arab Emirates", emoji: "🇦🇪" },
  { name: "United States", emoji: "🇺🇸" },
  { name: "Uruguay", emoji: "🇺🇾" },
  { name: "Uzbekistan", emoji: "🇺🇿" },
  { name: "Venezuela", emoji: "🇻🇪" },
  { name: "Vietnam", emoji: "🇻🇳" },
  { name: "Wales", emoji: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
  { name: "Yemen", emoji: "🇾🇪" },
  { name: "Zambia", emoji: "🇿🇲" },
  { name: "Zimbabwe", emoji: "🇿🇼" },
];

export function searchCountries(query: string): Country[] {
  if (!query) return countries.slice(0, 10);
  // Strip any leading emoji/flag characters for search (including regional indicators and tag sequences)
  const cleanQuery = query
    .replace(/^[\u{1F1E0}-\u{1F1FF}\u{1F3F4}\u{E0061}-\u{E007F}]+/u, "") // Regional indicators and tag sequences
    .replace(/^[\p{Emoji}\p{Emoji_Modifier}\p{Emoji_Component}\p{Emoji_Modifier_Base}\p{Emoji_Presentation}]+/u, "") // Other emojis
    .trim();
  if (!cleanQuery) return countries.slice(0, 10);
  const lowerQuery = cleanQuery.toLowerCase();
  return countries.filter((c) => c.name.toLowerCase().includes(lowerQuery));
}
