/**
 * Country Name → ISO 3166-1 Alpha-2 Code Mapping
 *
 * Used by CategoryHeader to resolve nation category values
 * (e.g., "France") to country codes for SVG flag rendering.
 *
 * Keys are lowercase for case-insensitive lookup.
 */

export const COUNTRY_NAME_TO_CODE: Record<string, string> = {
  // Major football nations
  'argentina': 'AR',
  'australia': 'AU',
  'austria': 'AT',
  'belgium': 'BE',
  'brazil': 'BR',
  'cameroon': 'CM',
  'canada': 'CA',
  'chile': 'CL',
  'china': 'CN',
  'colombia': 'CO',
  'costa rica': 'CR',
  'croatia': 'HR',
  'czech republic': 'CZ',
  'czechia': 'CZ',
  'denmark': 'DK',
  'ecuador': 'EC',
  'egypt': 'EG',
  'england': 'GB-ENG',
  'finland': 'FI',
  'france': 'FR',
  'germany': 'DE',
  'ghana': 'GH',
  'greece': 'GR',
  'hungary': 'HU',
  'iceland': 'IS',
  'iran': 'IR',
  'iraq': 'IQ',
  'ireland': 'IE',
  'republic of ireland': 'IE',
  'israel': 'IL',
  'italy': 'IT',
  'ivory coast': 'CI',
  "côte d'ivoire": 'CI',
  'jamaica': 'JM',
  'japan': 'JP',
  'korea republic': 'KR',
  'south korea': 'KR',
  'mexico': 'MX',
  'morocco': 'MA',
  'netherlands': 'NL',
  'the netherlands': 'NL',
  'holland': 'NL',
  'new zealand': 'NZ',
  'nigeria': 'NG',
  'north macedonia': 'MK',
  'northern ireland': 'GB-NIR',
  'norway': 'NO',
  'panama': 'PA',
  'paraguay': 'PY',
  'peru': 'PE',
  'poland': 'PL',
  'portugal': 'PT',
  'qatar': 'QA',
  'romania': 'RO',
  'russia': 'RU',
  'saudi arabia': 'SA',
  'scotland': 'GB-SCT',
  'senegal': 'SN',
  'serbia': 'RS',
  'slovakia': 'SK',
  'slovenia': 'SI',
  'south africa': 'ZA',
  'spain': 'ES',
  'sweden': 'SE',
  'switzerland': 'CH',
  'tunisia': 'TN',
  'turkey': 'TR',
  'türkiye': 'TR',
  'ukraine': 'UA',
  'united states': 'US',
  'usa': 'US',
  'uruguay': 'UY',
  'venezuela': 'VE',
  'wales': 'GB-WLS',
};
