/**
 * ISO country code → display name mapping for Who's That?.
 *
 * Covers all nationality_code values in the players table.
 * Used to convert the ISO codes stored in the DB into the
 * human-readable names used in puzzle answers and the CONTINENT_MAP.
 */

export const NATIONALITY_MAP: Record<string, string> = {
  // British home nations (GB subdivisions)
  'GB-ENG': 'England',
  'GB-SCT': 'Scotland',
  'GB-WLS': 'Wales',
  'GB-NIR': 'Northern Ireland',

  // Europe
  AD: 'Andorra',
  AL: 'Albania',
  AM: 'Armenia',
  AT: 'Austria',
  AZ: 'Azerbaijan',
  BA: 'Bosnia',
  BE: 'Belgium',
  BG: 'Bulgaria',
  BY: 'Belarus',
  CH: 'Switzerland',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  DE: 'Germany',
  DK: 'Denmark',
  EE: 'Estonia',
  ES: 'Spain',
  FI: 'Finland',
  FO: 'Faroe Islands',
  FR: 'France',
  GE: 'Georgia',
  GI: 'Gibraltar',
  GR: 'Greece',
  HR: 'Croatia',
  HU: 'Hungary',
  IE: 'Republic of Ireland',
  IS: 'Iceland',
  IT: 'Italy',
  LI: 'Liechtenstein',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  ME: 'Montenegro',
  MK: 'North Macedonia',
  NL: 'Netherlands',
  NO: 'Norway',
  PL: 'Poland',
  PT: 'Portugal',
  RO: 'Romania',
  RS: 'Serbia',
  RU: 'Russia',
  SE: 'Sweden',
  SI: 'Slovenia',
  SK: 'Slovakia',
  SM: 'San Marino',
  TR: 'Turkey',
  UA: 'Ukraine',
  XK: 'Kosovo',

  // South America
  AR: 'Argentina',
  BO: 'Bolivia',
  BR: 'Brazil',
  CL: 'Chile',
  CO: 'Colombia',
  EC: 'Ecuador',
  GF: 'French Guiana',
  GY: 'Guyana',
  PE: 'Peru',
  PY: 'Paraguay',
  SR: 'Suriname',
  UY: 'Uruguay',
  VE: 'Venezuela',

  // Africa
  AO: 'Angola',
  BF: 'Burkina Faso',
  BH: 'Bahrain',
  BI: 'Burundi',
  BJ: 'Benin',
  CD: 'DR Congo',
  CF: 'Central African Republic',
  CG: 'Congo',
  CI: 'Ivory Coast',
  CM: 'Cameroon',
  CV: 'Cape Verde',
  DZ: 'Algeria',
  EG: 'Egypt',
  GA: 'Gabon',
  GH: 'Ghana',
  GM: 'Gambia',
  GN: 'Guinea',
  GQ: 'Equatorial Guinea',
  GW: 'Guinea-Bissau',
  KE: 'Kenya',
  LR: 'Liberia',
  LY: 'Libya',
  MA: 'Morocco',
  MG: 'Madagascar',
  ML: 'Mali',
  MR: 'Mauritania',
  MZ: 'Mozambique',
  NG: 'Nigeria',
  SC: 'Seychelles',
  SL: 'Sierra Leone',
  SN: 'Senegal',
  TG: 'Togo',
  TN: 'Tunisia',
  TZ: 'Tanzania',
  ZA: 'South Africa',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',

  // North/Central America & Caribbean
  AG: 'Antigua and Barbuda',
  BB: 'Barbados',
  BM: 'Bermuda',
  CA: 'Canada',
  CR: 'Costa Rica',
  CW: 'Curacao',
  DO: 'Dominican Republic',
  GD: 'Grenada',
  GP: 'Guadeloupe',
  GT: 'Guatemala',
  HN: 'Honduras',
  HT: 'Haiti',
  JM: 'Jamaica',
  KN: 'Saint Kitts and Nevis',
  MQ: 'Martinique',
  MS: 'Montserrat',
  MX: 'Mexico',
  PA: 'Panama',
  SV: 'El Salvador',
  TT: 'Trinidad',
  US: 'United States',

  // Asia
  AE: 'UAE',
  BD: 'Bangladesh',
  CN: 'China',
  ID: 'Indonesia',
  IL: 'Israel',
  IN: 'India',
  IQ: 'Iraq',
  IR: 'Iran',
  JO: 'Jordan',
  JP: 'Japan',
  KH: 'Cambodia',
  KP: 'North Korea',
  KR: 'South Korea',
  LB: 'Lebanon',
  MY: 'Malaysia',
  OM: 'Oman',
  PH: 'Philippines',
  PK: 'Pakistan',
  QA: 'Qatar',
  SA: 'Saudi Arabia',
  SG: 'Singapore',
  TH: 'Thailand',
  UZ: 'Uzbekistan',
  VN: 'Vietnam',

  // Oceania
  AU: 'Australia',
  FJ: 'Fiji',
  NZ: 'New Zealand',
  PF: 'French Polynesia',
  BT: 'Bhutan',
};

/**
 * Convert an ISO nationality code to a display name.
 * Returns the code itself if no mapping exists.
 */
export function nationalityCodeToName(code: string): string {
  return NATIONALITY_MAP[code] ?? code;
}
