/**
 * Scout Report Share Page
 *
 * Web page for shared Scout Reports with dynamic OG meta tags for social media previews.
 * URL: /scout/[userId]
 *
 * When shared on WhatsApp, X, Facebook, etc., this page provides:
 * - Dynamic title with user's display name
 * - Dynamic description with tier and IQ points
 * - Dynamic OG image generated by /api/og/scout
 */

import { Metadata } from 'next';
import Link from 'next/link';
import { createAdminClient } from '@/lib/supabase/server';

// Tier thresholds (matching mobile app)
const IQ_TIERS = [
  { tier: 1, name: 'Trialist', minPoints: 0 },
  { tier: 2, name: 'Youth Team', minPoints: 25 },
  { tier: 3, name: 'Reserve Team', minPoints: 100 },
  { tier: 4, name: 'Impact Sub', minPoints: 250 },
  { tier: 5, name: 'Rotation Player', minPoints: 500 },
  { tier: 6, name: 'First Team Regular', minPoints: 1000 },
  { tier: 7, name: 'Key Player', minPoints: 2000 },
  { tier: 8, name: 'Club Legend', minPoints: 4000 },
  { tier: 9, name: 'National Treasure', minPoints: 8000 },
  { tier: 10, name: 'GOAT', minPoints: 20000 },
];

function getTierForPoints(totalIQ: number) {
  for (let i = IQ_TIERS.length - 1; i >= 0; i--) {
    if (totalIQ >= IQ_TIERS[i].minPoints) {
      return IQ_TIERS[i];
    }
  }
  return IQ_TIERS[0];
}

interface PageProps {
  params: Promise<{ userId: string }>;
}

async function getUserData(userId: string) {
  try {
    const supabase = await createAdminClient();
    const { data: profile, error } = await supabase
      .from('profiles')
      .select('display_name, total_iq')
      .eq('id', userId)
      .single();

    if (error || !profile) {
      return null;
    }

    return {
      displayName: profile.display_name || 'Football Fan',
      totalIQ: profile.total_iq || 0,
    };
  } catch {
    return null;
  }
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { userId } = await params;
  const userData = await getUserData(userId);

  const displayName = userData?.displayName || 'Football Fan';
  const totalIQ = userData?.totalIQ || 0;
  const tier = getTierForPoints(totalIQ);

  const title = `${displayName}'s Scout Report | Football IQ`;
  const description = `${tier.name} with ${totalIQ.toLocaleString()} IQ points. Test your football knowledge at Football IQ!`;

  // Use production URL for OG image
  const ogImageUrl = `https://football-iq.app/api/og/scout?userId=${userId}`;

  return {
    title,
    description,
    openGraph: {
      title: `${displayName}'s Scout Report`,
      description,
      type: 'website',
      images: [
        {
          url: ogImageUrl,
          width: 1200,
          height: 630,
          alt: `${displayName}'s Football IQ Scout Report`,
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title: `${displayName}'s Scout Report`,
      description,
      images: [ogImageUrl],
    },
  };
}

export default async function ScoutReportPage({ params }: PageProps) {
  const { userId } = await params;
  const userData = await getUserData(userId);

  const displayName = userData?.displayName || 'Football Fan';
  const totalIQ = userData?.totalIQ || 0;
  const tier = getTierForPoints(totalIQ);

  return (
    <main className="min-h-screen bg-[#0F172A] flex flex-col items-center justify-center p-6">
      <div className="max-w-md w-full text-center">
        {/* Logo/Header */}
        <div className="mb-8">
          <h1 className="text-[#58CC02] text-3xl font-bold tracking-wider mb-2">
            FOOTBALL IQ
          </h1>
          <p className="text-slate-400 text-sm tracking-widest uppercase">
            Scout Report
          </p>
        </div>

        {/* User Card */}
        <div className="bg-[#1a2744] rounded-2xl p-8 border-2 border-[#58CC02] mb-8">
          <div className="mb-4">
            <span
              className="inline-block px-4 py-1 rounded-full text-sm font-semibold"
              style={{
                backgroundColor: getTierColor(tier.tier),
                color: '#0F172A',
              }}
            >
              {tier.name}
            </span>
          </div>

          <div className="mb-4">
            <p className="text-4xl font-bold" style={{ color: getTierColor(tier.tier) }}>
              {totalIQ.toLocaleString()}
            </p>
            <p className="text-slate-400 text-xs tracking-widest uppercase mt-1">
              IQ Points
            </p>
          </div>

          <p className="text-white text-xl font-semibold">{displayName}</p>
        </div>

        {/* CTA */}
        <div className="space-y-4">
          <p className="text-slate-300 mb-4">
            Want to test your football knowledge and build your own Scout Report?
          </p>

          <Link
            href="/"
            className="inline-block w-full bg-[#58CC02] text-[#0F172A] font-bold py-4 px-8 rounded-xl text-lg hover:bg-[#4db300] transition-colors"
          >
            Get Started
          </Link>

          <p className="text-slate-500 text-sm">
            Download Football IQ on iOS or Android
          </p>
        </div>
      </div>

      {/* Footer */}
      <footer className="mt-12 text-slate-500 text-sm">
        <p>football-iq.app</p>
      </footer>
    </main>
  );
}

// Tier color helper
function getTierColor(tier: number): string {
  const colors: Record<number, string> = {
    1: '#94A3B8',
    2: '#6B7280',
    3: '#3B82F6',
    4: '#22C55E',
    5: '#58CC02',
    6: '#58CC02',
    7: '#FACC15',
    8: '#F59E0B',
    9: '#F97316',
    10: '#FFD700',
  };
  return colors[Math.min(Math.max(tier, 1), 10)];
}
